/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-03-2013
 * 
 * XDoclet definition:
 * @struts.form name="addNewCreditForm"
 */
public class AddNewCreditForm extends ValidatorForm {
	/*
	 * Generated Methods
	 */
	/** phonenumber property */
	private String phonenumber;

	/** addrline1 property */
	private String addrline1;

	/** addrline2 property */
	private String addrline2;

	/** zipcode property */
	private String zipcode;

	/** company property */
	private String company;

	/** state property */
	private String state;

	/** lastname property */
	private String lastname;

	/** firstname property */
	private String firstname;

	/** city property */
	private String city;
    
	private long cardnumber;
	
	private String nameoncard;
	
	private int cardcvv2;
	
	private String month;
	
	private String year;
	
	private String cardtype;
	
	
	public String getPhonenumber() {
		return phonenumber;
	}


	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}


	public String getAddrline1() {
		return addrline1;
	}


	public void setAddrline1(String addrline1) {
		this.addrline1 = addrline1;
	}


	public String getAddrline2() {
		return addrline2;
	}


	public void setAddrline2(String addrline2) {
		this.addrline2 = addrline2;
	}


	public String getZipcode() {
		return zipcode;
	}


	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}


	public String getCompany() {
		return company;
	}


	public void setCompany(String company) {
		this.company = company;
	}


	public String getState() {
		return state;
	}


	public void setState(String state) {
		this.state = state;
	}


	public String getLastname() {
		return lastname;
	}


	public void setLastname(String lastname) {
		this.lastname = lastname;
	}


	public String getFirstname() {
		return firstname;
	}


	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}


	public String getCity() {
		return city;
	}


	public void setCity(String city) {
		this.city = city;
	}


	public long getCardnumber() {
		return cardnumber;
	}


	public void setCardnumber(long cardnumber) {
		this.cardnumber = cardnumber;
	}


	public String getNameoncard() {
		return nameoncard;
	}


	public void setNameoncard(String nameoncard) {
		this.nameoncard = nameoncard;
	}


	public int getCardcvv2() {
		return cardcvv2;
	}


	public void setCardcvv2(int cardcvv2) {
		this.cardcvv2 = cardcvv2;
	}


	public String getMonth() {
		return month;
	}


	public void setMonth(String month) {
		this.month = month;
	}


	public String getYear() {
		return year;
	}


	public void setYear(String year) {
		this.year = year;
	}


	public String getCardtype() {
		return cardtype;
	}


	public void setCardtype(String cardtype) {
		this.cardtype = cardtype;
	}


	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}