/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-02-2013
 * 
 * XDoclet definition:
 * @struts.form name="addNewAddressForm"
 */
public class AddNewAddressForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** phonenumber property */
	private String phonenumber;

	/** addrline1 property */
	private String addrline1;

	/** addrline2 property */
	private String addrline2;

	/** zipcode property */
	private String zipcode;

	/** company property */
	private String company;

	/** state property */
	private String state;

	/** lastname property */
	private String lastname;

	/** firstname property */
	private String firstname;

	/** city property */
	private String city;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the phonenumber.
	 * @return String
	 */
	public String getPhonenumber() {
		return phonenumber;
	}

	/** 
	 * Set the phonenumber.
	 * @param phonenumber The phonenumber to set
	 */
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	/** 
	 * Returns the addrline1.
	 * @return String
	 */
	public String getAddrline1() {
		return addrline1;
	}

	/** 
	 * Set the addrline1.
	 * @param addrline1 The addrline1 to set
	 */
	public void setAddrline1(String addrline1) {
		this.addrline1 = addrline1;
	}

	/** 
	 * Returns the addrline2.
	 * @return String
	 */
	public String getAddrline2() {
		return addrline2;
	}

	/** 
	 * Set the addrline2.
	 * @param addrline2 The addrline2 to set
	 */
	public void setAddrline2(String addrline2) {
		this.addrline2 = addrline2;
	}

	/** 
	 * Returns the zipcode.
	 * @return String
	 */
	public String getZipcode() {
		return zipcode;
	}

	/** 
	 * Set the zipcode.
	 * @param zipcode The zipcode to set
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	/** 
	 * Returns the company.
	 * @return String
	 */
	public String getCompany() {
		return company;
	}

	/** 
	 * Set the company.
	 * @param company The company to set
	 */
	public void setCompany(String company) {
		this.company = company;
	}

	/** 
	 * Returns the state.
	 * @return String
	 */
	public String getState() {
		return state;
	}

	/** 
	 * Set the state.
	 * @param state The state to set
	 */
	public void setState(String state) {
		this.state = state;
	}

	/** 
	 * Returns the lastname.
	 * @return String
	 */
	public String getLastname() {
		return lastname;
	}

	/** 
	 * Set the lastname.
	 * @param lastname The lastname to set
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/** 
	 * Returns the firstname.
	 * @return String
	 */
	public String getFirstname() {
		return firstname;
	}

	/** 
	 * Set the firstname.
	 * @param firstname The firstname to set
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/** 
	 * Returns the city.
	 * @return String
	 */
	public String getCity() {
		return city;
	}

	/** 
	 * Set the city.
	 * @param city The city to set
	 */
	public void setCity(String city) {
		this.city = city;
	}
}