/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorActionForm;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-07-2013
 * 
 * XDoclet definition:
 * @struts.form name="registerForm"
 */
public class RegisterForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** addressline2 property */
	private String addressline2;


	/** phone property */
	private String phone;

	/** username property */
	private String username;

	/** addressline1 property */
	private String addressline1;

	/** email property */
	private String email;

	/** lastname property */
	private String lastname;

	/** firstname property */
	private String firstname;

	/** password property */
	private String password;

	/** passwordsalt property */
	private String passwordsalt;
	
	private String state;
	
	private String city;
	
	private int zipcode;
	
	private String company;


	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the addressline2.
	 * @return String
	 */
	public String getAddressline2() {
		return addressline2;
	}
    
	
	public int getZipcode() {
		return zipcode;
	}

	public void setZipcode(int zipcode) {
		this.zipcode = zipcode;
	}

	/** 
	 * Set the addressline2.
	 * @param addressline2 The addressline2 to set
	 */
	public void setAddressline2(String addressline2) {
		this.addressline2 = addressline2;
	}



	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the addressline1.
	 * @return String
	 */
	public String getAddressline1() {
		return addressline1;
	}

	/** 
	 * Set the addressline1.
	 * @param addressline1 The addressline1 to set
	 */
	public void setAddressline1(String addressline1) {
		this.addressline1 = addressline1;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the lastname.
	 * @return String
	 */
	public String getLastname() {
		return lastname;
	}

	/** 
	 * Set the lastname.
	 * @param lastname The lastname to set
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/** 
	 * Returns the firstname.
	 * @return String
	 */
	public String getFirstname() {
		return firstname;
	}

	/** 
	 * Set the firstname.
	 * @param firstname The firstname to set
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/** 
	 * Returns the passwordsalt.
	 * @return String
	 */
	public String getPasswordsalt() {
		return passwordsalt;
	}

	/** 
	 * Set the passwordsalt.
	 * @param passwordsalt The passwordsalt to set
	 */
	public void setPasswordsalt(String passwordsalt) {
		this.passwordsalt = passwordsalt;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	

	

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}
	
	
}