/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-31-2013
 * 
 * XDoclet definition:
 * @struts.form name="updateBookForm"
 */
public class UpdateBookForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	private String stockquantity;
	private String unitprice;
	
	








	public String getStockquantity() {
		return stockquantity;
	}










	public void setStockquantity(String stockquantity) {
		this.stockquantity = stockquantity;
	}










	public String getUnitprice() {
		return unitprice;
	}










	public void setUnitprice(String unitprice) {
		this.unitprice = unitprice;
	}










	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

}