/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.sql.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Address;
import po.User;

import dao.IUserDao;
import database.form.AddNewAddressForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-02-2013
 * 
 * XDoclet definition:
 * @struts.action path="/addNewAddress" name="addNewAddressForm" input="/addNewAddress.jsp" scope="request" validate="true"
 */
public class AddNewAddressAction extends Action {
	/*
	 * Generated Methods
	 */
     private IUserDao udao;
     
     
	public IUserDao getUdao() {
		return udao;
	}


	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddNewAddressForm addNewAddressForm = (AddNewAddressForm) form;// TODO Auto-generated method stub
		User user=(User) request.getSession().getAttribute("user");
		int userId=user.getID();

		String firstname=addNewAddressForm.getFirstname();
		String lastname=addNewAddressForm.getLastname();
		String phonenumber=addNewAddressForm.getPhonenumber();
		String state=addNewAddressForm.getState();
		String city=addNewAddressForm.getCity();
		String company=addNewAddressForm.getCompany();
		String addrline1=addNewAddressForm.getAddrline1();
		String addrline2=addNewAddressForm.getAddrline2();
		int zipcode=Integer.parseInt(addNewAddressForm.getZipcode());
		Date date =new Date(System.currentTimeMillis());
		Address address=new Address(firstname,lastname,state,city,zipcode,company,phonenumber,date,addrline1,addrline2);
		boolean flag=udao.addNewAddress(userId, address);
		if(flag!=false){
			request.setAttribute("newAddress", 1);
		}else{
			request.setAttribute("newAddress", 0);
		}
		return mapping.getInputForward();
	}
}