/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Address;
import po.Credit;

import dao.IUserDao;
import database.form.CheckCreditForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-03-2013
 * 
 * XDoclet definition:
 * @struts.action path="/checkCredit" name="checkCreditForm" input="/manageCredit.jsp" scope="request" validate="true"
 */
public class CheckCreditAction extends Action {
	/*
	 * Generated Methods
	 */
    private IUserDao udao;
	
	
	public IUserDao getUdao() {
		return udao;
	}


	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CheckCreditForm checkCreditForm = (CheckCreditForm) form;// TODO Auto-generated method stub
		String number=checkCreditForm.getCardnumber();
		System.out.println(number);
		Credit credit=udao.checkCredit(Long.parseLong(number));
		
		request.getSession().setAttribute("creditnumber", number);
		request.getSession().setAttribute("editCredit", credit);
		return new ActionForward("/updateCredit.jsp");
	}
}