/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dao.IUserDao;

/** 
 * MyEclipse Struts
 * Creation date: 04-10-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class IndexAction extends Action {
	/*
	 * Generated Methods
	 */
    private IUserDao udao;
    
	public IUserDao getUdao() {
		return udao;
	}

	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ArrayList books=(ArrayList) request.getSession().getAttribute("topbook");
		if(books==null){
			books=udao.selectTopBook();
			request.getSession().setAttribute("topbook", books);
		}
		return new ActionForward("/index.jsp");
	}
}