/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.sql.Date;

import dao.IEmployeeDAO;
import database.form.InsertBookForm;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import po.Book;

/** 
 * MyEclipse Struts
 * Creation date: 03-13-2013
 * 
 * XDoclet definition:
 * @struts.action path="/insertBook" name="insertBookForm" input="/insertBook.jsp" scope="request" validate="true"
 */
public class InsertBookAction extends Action {
	/*
	 * Generated Methods
	 */
    private IEmployeeDAO edao;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
    
    public IEmployeeDAO getEdao() {
		return edao;
	}
	public void setEdao(IEmployeeDAO edao) {
		this.edao = edao;
	}
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InsertBookForm insertBookForm = (InsertBookForm) form;// TODO Auto-generated method stub
		boolean flag;
		long ISBN=insertBookForm.getISBN();
		flag=edao.getBookByISBN(ISBN);
		if(!flag){
			
			Integer sq=insertBookForm.getStockquantity();
			Double up=insertBookForm.getUnitprice();
			String booktitle=insertBookForm.getBookTitle();
			String author=insertBookForm.getAuthor();
			String publishtime=insertBookForm.getPublishTime();
			Date createon=new Date(System.currentTimeMillis());
			String description=insertBookForm.getDescription();
			String image=insertBookForm.getImage();
			Book book=new Book(ISBN,sq,up,booktitle,author,publishtime,createon,description,image);
			edao.InsertBook(book);
			request.getSession().setAttribute("book", book);
		
		}else{
			ActionMessages errors=new ActionMessages();
			ActionMessage error=new ActionMessage("error.book",ISBN);
			errors.add("book",error);
			this.saveErrors(request, errors);
			return mapping.getInputForward();
		}
	
		return new ActionForward("/index.jsp");
	}
	
}