/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.util.ArrayList;
import resources.PageController;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


import dao.IEmployeeDAO;


/** 
 * MyEclipse Struts
 * Creation date: 03-28-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class QueryUserAction extends Action {
	/*
	 * Generated Methods
	 */
	 private IEmployeeDAO edao;
    



	public IEmployeeDAO getEdao() {
		return edao;
	}




	public void setEdao(IEmployeeDAO edao) {
		this.edao = edao;
	}




	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String str=request.getParameter("PageIndex");
		if(str==null){
			str="1";
		}
		int currentPageIndex=Integer.parseInt(str);
		PageController pc=(PageController)request.getAttribute("pc");
		if(pc==null){
			pc=new PageController();
			ArrayList users=edao.QueryUser();
			pc.setBigList(users);
			request.setAttribute("pc", pc);
			
		}
		pc.setCurrentPageIndex(currentPageIndex);
		
		return new ActionForward("/queryuser.jsp");
	}
}