/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.sql.Timestamp;
import java.sql.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import po.Address;
import po.User;

import dao.IUserDao;
import database.form.RegisterForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-07-2013
 * 
 * XDoclet definition:
 * @struts.action input="/register.jsp" scope="request" validate="true"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */
    private IUserDao udao;
   
	public IUserDao getUdao() {
		return udao;
	}

	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		RegisterForm registerform= (RegisterForm) form;
		String username=registerform.getUsername();
		User user=udao.getUserByUsername(username);
		System.out.println("1111");
		if(user==null){
			
			String firstname=registerform.getFirstname();
			String lastname=registerform.getLastname();
			String password=registerform.getPassword();
			String passwordsalt=registerform.getPasswordsalt();
			String phonenumber=registerform.getPhone();
			String state=registerform.getState();
			String city=registerform.getCity();
			String company=registerform.getCompany();
			String addrline1=registerform.getAddressline1();
			String addrline2=registerform.getAddressline2();
			int zipcode=registerform.getZipcode();
			String email=registerform.getEmail();
			Date date =new Date(System.currentTimeMillis());
			System.out.println(date);
			Timestamp timestamp=new Timestamp(System.currentTimeMillis());
			
			Address address=new Address(lastname,firstname,state,city,zipcode,company,phonenumber,date,addrline1,addrline2);
			boolean flag1=udao.insertAddress(address);
			User user2=new User(username,password,passwordsalt,email,timestamp);
			boolean flag2=udao.insertUser(user2);
			//System.out.println("insert");
			request.getSession().setAttribute("user",user);
			if(flag1 &&flag2){
				return new ActionForward("/index.jsp");
			}else{
				ActionMessages errors=new ActionMessages();
				ActionMessage error=new ActionMessage("error.register",username);
				errors.add("register",error);
				this.saveErrors(request, errors);
				return new ActionForward("/register.jsp");
			}
			    
		}else{
			ActionMessages errors=new ActionMessages();
			ActionMessage error=new ActionMessage("error.register",username);
			errors.add("register",error);
			this.saveErrors(request, errors);
			return new ActionForward("/register.jsp");	
			
		}
	}

}