/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.sql.Date;
import java.sql.Timestamp;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import po.Address;
import po.User;

import dao.IUserDao;
import database.form.UserRegisterForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-28-2013
 * 
 * XDoclet definition:
 * @struts.action path="/userRegister" name="userRegisterForm" input="/userRegister.jsp" scope="request" validate="true"
 */
public class UserRegisterAction extends Action {
	/*
	 * Generated Methods
	 */
     private IUserDao udao;
     
     
	public IUserDao getUdao() {
		return udao;
	}


	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserRegisterForm userRegisterForm = (UserRegisterForm) form;// TODO Auto-generated method stub
		String username=userRegisterForm.getUsername();
		User user=udao.getUserByUsername(username);
		System.out.println("1111");
		if(user==null){
			
			String firstname=userRegisterForm.getFirstname();
			String lastname=userRegisterForm.getLastname();
			String password=userRegisterForm.getPassword();
			String passwordsalt=userRegisterForm.getPasswordsalt();
			String phonenumber=userRegisterForm.getPhone();
			String state=userRegisterForm.getState();
			String city=userRegisterForm.getCity();
			String company=userRegisterForm.getCompany();
			String addrline1=userRegisterForm.getAddressline1();
			String addrline2=userRegisterForm.getAddressline2();
			int zipcode=Integer.parseInt(userRegisterForm.getZipcode());
			String email=userRegisterForm.getEmail();
			Date date =new Date(System.currentTimeMillis());
			System.out.println(date);
			Timestamp timestamp=new Timestamp(System.currentTimeMillis());
			
			Address address=new Address(lastname,firstname,state,city,zipcode,company,phonenumber,date,addrline1,addrline2);
			udao.insertAddress(address);
			User user2=new User(username,password,passwordsalt,email,timestamp);
			udao.insertUser(user2);
			//System.out.println("insert");
			request.getSession().setAttribute("user",user);
			return new ActionForward("/index.jsp");
		}else{
			ActionMessages errors=new ActionMessages();
			ActionMessage error=new ActionMessage("error.register",username);
			errors.add("register",error);
			this.saveErrors(request, errors);
			return mapping.getInputForward();
			
		}

	}
}