/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.sql.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Credit;
import po.User;

import dao.IUserDao;
import database.form.AddNewCreditForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-03-2013
 * 
 * XDoclet definition:
 * @struts.action path="/addNewCredit" name="addNewCreditForm" input="/addNewCredit.jsp" scope="request" validate="true"
 */
public class AddNewCreditAction extends Action {
	/*
	 * Generated Methods
	 */
    private IUserDao udao;
    
	public IUserDao getUdao() {
		return udao;
	}

	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddNewCreditForm addNewCreditForm = (AddNewCreditForm) form;// TODO Auto-generated method stub
		User user=(User) request.getSession().getAttribute("user");
		int cid=user.getID();
		Date ex=new Date(0);
		long cardnumber=addNewCreditForm.getCardnumber();
		String name=addNewCreditForm.getNameoncard();
		int cardcvv2=addNewCreditForm.getCardcvv2();
		String cardtype=addNewCreditForm.getCardtype();
		String date=addNewCreditForm.getYear()+"-"+addNewCreditForm.getMonth()+"-01";
		ex=Date.valueOf(date);
		System.out.println(ex);
		String firstname=addNewCreditForm.getFirstname();
		String lastname=addNewCreditForm.getLastname();
		String phonenumber=addNewCreditForm.getPhonenumber();
		String state=addNewCreditForm.getState();
		String city=addNewCreditForm.getCity();
		String company=addNewCreditForm.getCompany();
		String addrline1=addNewCreditForm.getAddrline1();
		String addrline2=addNewCreditForm.getAddrline2();
		int zipcode=Integer.parseInt(addNewCreditForm.getZipcode());
		Credit credit=new Credit(cardnumber,name,ex,cardcvv2,cardtype,lastname,firstname,state,city,company,zipcode,phonenumber,addrline1,addrline2);
		boolean flag=udao.addNewCredit(cid, credit);
		if(flag!=false){
			request.setAttribute("newCredit", 1);
		}else{
			request.setAttribute("newCredit", 0);
		}
		return mapping.getInputForward();
	}
}