/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Book;
import po.Order;
import po.User;
import database.form.AddToShoppingCartForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-04-2013
 * 
 * XDoclet definition:
 * @struts.action path="/addToShoppingCart" name="addToShoppingCartForm" input="/addToShoppingCart.jsp" scope="request" validate="true"
 */
public class AddToShoppingCartAction extends Action {
	/*
	 * Generated Methods
	 */
    
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddToShoppingCartForm addToShoppingCartForm = (AddToShoppingCartForm) form;// TODO Auto-generated method stub
		int quantity=addToShoppingCartForm.getQuantity();
		Book book=(Book)request.getSession().getAttribute("searchBook");
		double price=book.getUnitprice();
		float amount=(float) (price*quantity);
		User user=(User)request.getSession().getAttribute("user");
		Timestamp time=new Timestamp(System.currentTimeMillis());
		int uid=user.getID();
		int booksku=book.getBooksku();
		String status="processing";
		ArrayList shoppingcart=(ArrayList) request.getSession().getAttribute("shoppingcart");
		if(shoppingcart==null){
			shoppingcart=new ArrayList();
		}
		Order order=new Order(uid,booksku,quantity,status,time,amount);
		shoppingcart.add(order);
		request.getSession().setAttribute("shoppingcart", shoppingcart);
		return new ActionForward("/index.do");
	}
}