/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import dao.IEmployeeDAO;
import database.form.AdvanceSelectForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-06-2013
 * 
 * XDoclet definition:
 * @struts.action path="/advanceSelect" name="advanceSelectForm" input="/advanceSelect.jsp" scope="request" validate="true"
 */
public class AdvanceSelectAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
    private IEmployeeDAO edao;
    
    
	public IEmployeeDAO getEdao() {
		return edao;
	}


	public void setEdao(IEmployeeDAO edao) {
		this.edao = edao;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	public ActionForward book(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdvanceSelectForm advanceSelectForm = (AdvanceSelectForm) form;// TODO Auto-generated method stub
		String from=advanceSelectForm.getFrom();
		String to=advanceSelectForm.getTo();
		ArrayList books=edao.advanceSelectTopBook(from, to);
		//System.out.println(books);
		if(books!=null){
			request.setAttribute("advanceResult", books);
			request.setAttribute("advance", 1);
		}else{
			request.setAttribute("advance", 0);
		}
		return mapping.getInputForward();
	}
	public ActionForward sale(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdvanceSelectForm advanceSelectForm = (AdvanceSelectForm) form;// TODO Auto-generated method stub
		String from=advanceSelectForm.getFrom();
		String to=advanceSelectForm.getTo();
		ArrayList sales=edao.advanceSelectTopSale(from, to);
		//System.out.println(sales);
		if(sales!=null){
			request.setAttribute("advanceResult", sales);
			request.setAttribute("advance", 2);
		}else{
			request.setAttribute("advance", 0);
		}
		return mapping.getInputForward();
	}
	public ActionForward buyer(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdvanceSelectForm advanceSelectForm = (AdvanceSelectForm) form;// TODO Auto-generated method stub
		String from=advanceSelectForm.getFrom();
		String to=advanceSelectForm.getTo();
		ArrayList buyers=edao.advanceSelectTopBuyer(from, to);
		//System.out.println(buyers);
		if(buyers!=null){
			request.setAttribute("advanceResult", buyers);
			request.setAttribute("advance", 3);
		}else{
			request.setAttribute("advance", 0);
		}
		return mapping.getInputForward();
	}
	public ActionForward supplier(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdvanceSelectForm advanceSelectForm = (AdvanceSelectForm) form;// TODO Auto-generated method stub
		String from=advanceSelectForm.getFrom();
		String to=advanceSelectForm.getTo();
		ArrayList suppliers=edao.advanceSelectTopSupplier(from, to);
		//System.out.println(suppliers);
		if(suppliers!=null){
			request.setAttribute("advanceResult", suppliers);
			request.setAttribute("advance", 4);
		}else{
			request.setAttribute("advance", 0);
		}
		return mapping.getInputForward();
	}
}