/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Address;
import po.Book;

import dao.IUserDao;

/** 
 * MyEclipse Struts
 * Creation date: 04-04-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CheckDetailsAction extends Action {
	/*
	 * Generated Methods
	 */
    private IUserDao udao;
    
    
	public IUserDao getUdao() {
		return udao;
	}


	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		int oid=Integer.parseInt(request.getParameter("id"));
		Address address=udao.shipDetails(oid);
		Book book=udao.bookDetails(oid);
		if(address!=null){
			request.setAttribute("ship", address);
			request.setAttribute("bdetail", book);
		}
		return new ActionForward("/orderDetails.jsp");
	}
}