/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.util.ArrayList;
import java.util.Iterator;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Order;
import po.User;

import dao.IUserDao;
import database.form.ChoosePaymentForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-04-2013
 * 
 * XDoclet definition:
 * @struts.action path="/choosePayment" name="choosePaymentForm" input="/chooseShippingAddress.jsp" scope="request" validate="true"
 */
public class ChoosePaymentAction extends Action {
	/*
	 * Generated Methods
	 */
    private IUserDao udao;
    
    
	public IUserDao getUdao() {
		return udao;
	}


	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ChoosePaymentForm choosePaymentForm = (ChoosePaymentForm) form;// TODO Auto-generated method stub
		User user=(User)request.getSession().getAttribute("user");
		int cid=user.getID();
		int aid=Integer.parseInt(choosePaymentForm.getAid());
		System.out.println(aid);
		System.out.println(cid);
		ArrayList orders=(ArrayList) request.getSession().getAttribute("shoppingcart");
		ArrayList orders2=new ArrayList();
		Iterator p=orders.iterator();
		ArrayList credits=udao.queryCredit(cid);
		while(p.hasNext()){
			Order o=(Order) p.next();
			o.setShippingAddress(aid);
			orders2.add(o);
		}
		request.getSession().setAttribute("shoppingcart", orders2);
		if(credits!=null){
			request.setAttribute("choose", 1);
			request.getSession().setAttribute("creditlist", credits);
		}else{
			request.setAttribute("choose", 0);
		}
		return new ActionForward("/choosePayment.jsp");
	}
}