/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.User;

import dao.IUserDao;

/** 
 * MyEclipse Struts
 * Creation date: 04-03-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class DeleteAddressAction extends Action {
	/*
	 * Generated Methods
	 */
    private IUserDao udao;
    
	public IUserDao getUdao() {
		return udao;
	}

	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		User user=(User) request.getSession().getAttribute("user");
		int did=user.getDefaultShippingAddress();
		String id=request.getParameter("id");
		System.out.println(id);
		if(did!=Integer.parseInt(id)){
			boolean flag=udao.deleteAddress(Integer.parseInt(id));
			if(flag!=false){
				request.setAttribute("noAddress", 1);
			}else{
				request.setAttribute("noAddress", 0);
			}
		}else{
			request.setAttribute("default",1);
		}
		
		return new ActionForward("/manageAddress.do");
	}
}