package database.action;
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import po.Employee;

import dao.IEmployeeDAO;
import database.form.employeeLoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-07-2013
 * 
 * XDoclet definition:
 * @struts.action path="/employeeLogin" name="userLoginForm" input="/employeeLogin" scope="request" validate="true"
 */
public class employeeLoginAction extends Action {
	/*
	 * Generated Methods
	 */
     private IEmployeeDAO edao;
     
     
	public IEmployeeDAO getEdao() {
		return edao;
	}


	public void setEdao(IEmployeeDAO edao) {
		this.edao = edao;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		employeeLoginForm employeeLogin = (employeeLoginForm) form;// TODO Auto-generated method stub
		String loginname=employeeLogin.getLoginname();
		String password=employeeLogin.getPassword();
		Employee employee=edao.getUserByUsername(loginname);
		ActionMessages errors=new ActionMessages();
		if(employee==null||!employee.getPassword().equals(password)){
			ActionMessage error=new ActionMessage("errors.employee");
			errors.add("employeelogin",error);
			this.saveErrors(request,errors);
			return mapping.getInputForward();
		}
		request.getSession().setAttribute("employee",employee);
		return new ActionForward("/index.jsp");
	}
}