/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Address;
import po.Book;
import po.Order;

import dao.IEmployeeDAO;
import dao.IUserDao;
import database.form.QueryOneOrderForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-06-2013
 * 
 * XDoclet definition:
 * @struts.action path="/queryOneOrder" name="queryOneOrderForm" input="/queryOneOrder.jsp" scope="request" validate="true"
 */
public class QueryOneOrderAction extends Action {
	/*
	 * Generated Methods
	 */
    private IEmployeeDAO edao;
    
    private IUserDao udao;
    
	public IEmployeeDAO getEdao() {
		return edao;
	}

	public void setEdao(IEmployeeDAO edao) {
		this.edao = edao;
	}

	public IUserDao getUdao() {
		return udao;
	}

	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		QueryOneOrderForm queryOneOrderForm = (QueryOneOrderForm) form;// TODO Auto-generated method stub
		int id=queryOneOrderForm.getId();
		Order order=edao.getOrderbyId(id);
		if(order!=null){
			request.getSession().setAttribute("uorder", order);
			Book book=edao.getBookByBooksku(order.getSku());
			request.getSession().setAttribute("ubook", book);
			Address address=udao.checkAddress(order.getShippingAddress());
			request.getSession().setAttribute("uaddr", address);
		}else{
			request.getSession().setAttribute("uorder",null);
			request.setAttribute("exist",0);
		}
		return mapping.getInputForward();
	}
}