/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Book;

import dao.IEmployeeDAO;
import database.form.QueryOneBookForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-31-2013
 * 
 * XDoclet definition:
 * @struts.action path="/queryOneBook" name="queryOneBookForm" input="/queryOneBook.jsp" scope="request" validate="true"
 */
public class QueryOneBookAction extends Action {
	/*
	 * Generated Methods
	 */
    private IEmployeeDAO edao;
    
	public IEmployeeDAO getEdao() {
		return edao;
	}

	public void setEdao(IEmployeeDAO edao) {
		this.edao = edao;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		QueryOneBookForm queryOneBookForm = (QueryOneBookForm) form;// TODO Auto-generated method stub
		int booksku=Integer.parseInt(queryOneBookForm.getBooksku());
		Book book=edao.getBookByBooksku(booksku);
		if(book !=null){
			request.getSession().setAttribute("requiredBook", book);
		}else{
			request.getSession().setAttribute("requiredBook", null);
			request.setAttribute("exist", 0);
		}
		return mapping.getInputForward();
	}
}