/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Book;

import dao.IUserDao;
import database.form.SearchBookForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-01-2013
 * 
 * XDoclet definition:
 * @struts.action path="/searchBook" name="searchBookForm" input="/searchBook.jsp" scope="request" validate="true"
 */
public class SearchBookAction extends Action {
	/*
	 * Generated Methods
	 */
    private IUserDao udao;
    
	public IUserDao getUdao() {
		return udao;
	}

	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchBookForm searchBookForm = (SearchBookForm) form;// TODO Auto-generated method stub
		ArrayList Books=new ArrayList();
		String attribute=searchBookForm.getAttribute();
		String value=searchBookForm.getValue();
		//System.out.println(attribute);
		//System.out.println(value);
	    Books=udao.searchBook(attribute, value);
	    if(Books!=null){
	    	request.setAttribute("search",1);
	    	request.setAttribute("searchBook", Books);
	    }else{
	    	request.setAttribute("search",0);
	    }
		return mapping.getInputForward();
	}
}