/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dao.IEmployeeDAO;

/** 
 * MyEclipse Struts
 * Creation date: 04-06-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SelectTopSaleAction extends Action {
	/*
	 * Generated Methods
	 */
private IEmployeeDAO edao;
    
    
	public IEmployeeDAO getEdao() {
		return edao;
	}


	public void setEdao(IEmployeeDAO edao) {
		this.edao = edao;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ArrayList sale=edao.selectTopSale();
		if(sale!=null&&sale.size()!=0){
		request.setAttribute("topsale", sale);
		}else{
			request.setAttribute("topsale", 0);
		}
		
		return new ActionForward("/selectTopSale.jsp");
	}
}