/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Order;

import dao.IEmployeeDAO;
import database.form.UpdateOrderForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-06-2013
 * 
 * XDoclet definition:
 * @struts.action path="/updateOrder" name="updateOrderForm" input="/updateOrder.jsp" scope="request" validate="true"
 */
public class UpdateOrderAction extends Action {
	/*
	 * Generated Methods
	 */
    private IEmployeeDAO edao;
    
	public IEmployeeDAO getEdao() {
		return edao;
	}

	public void setEdao(IEmployeeDAO edao) {
		this.edao = edao;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UpdateOrderForm updateOrderForm = (UpdateOrderForm) form;// TODO Auto-generated method stub
		String status=updateOrderForm.getStatus();
		int eid=Integer.parseInt(updateOrderForm.getEid());
		Order order=(Order) request.getSession().getAttribute("uorder");
		int id=order.getId();
		boolean flag=edao.updateOrder(eid, status, id);
		if(flag!=false){
			Order order2=edao.getOrderbyId(id);
			request.getSession().setAttribute("uorder", order2);
			request.setAttribute("update", 1);
	    }else{
	    	request.setAttribute("update", 0);
	    }
		return mapping.getInputForward();
	}
}