/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.User;

import dao.IUserDao;
import database.form.UpdateUserForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-02-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UpdateUserAction extends Action {
	
	private IUserDao udao;
	
	
	/*
	 * Generated Methods
	 */

	public IUserDao getUdao() {
		return udao;
	}


	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		UpdateUserForm updateuserform=(UpdateUserForm)form;
		User user=(User)request.getSession().getAttribute("user");
		String username=user.getUsername();
		String password=updateuserform.getPassword();
		String ps=updateuserform.getPasswordSalt();
		String email=updateuserform.getEmail();
		User user2=new User(username,password,ps,email);
		boolean flag=udao.updateUser(user2);
		if(flag!=false){
			request.setAttribute("update", 1);
		}else{
			request.setAttribute("update", 0);
		}
		return mapping.getInputForward();
	}
}