/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Address;

import dao.IUserDao;
import database.form.UpdateAddressForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-02-2013
 * 
 * XDoclet definition:
 * @struts.action path="/updateAddress" name="updateAddressForm" input="/updateAddress.jsp" scope="request" validate="true"
 */
public class UpdateAddressAction extends Action {
	/*
	 * Generated Methods
	 */
    private IUserDao udao;
    
	public IUserDao getUdao() {
		return udao;
	}

	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UpdateAddressForm updateAddressForm = (UpdateAddressForm) form;// TODO Auto-generated method stub
		int id=Integer.parseInt((String) request.getSession().getAttribute("addressid"));
		
		System.out.println(id);
		String firstname=updateAddressForm.getFirstname();
		String lastname=updateAddressForm.getLastname();
		String phonenumber=updateAddressForm.getPhonenumber();
		String state=updateAddressForm.getState();
		String city=updateAddressForm.getCity();
		String company=updateAddressForm.getCompany();
		String addrline1=updateAddressForm.getAddr1();
		String addrline2=updateAddressForm.getAddr2();
		int zipcode=Integer.parseInt(updateAddressForm.getZipcode());
		Address address=new Address(id,firstname,lastname,company,state,phonenumber,zipcode,city,addrline1,addrline2);
		boolean flag=udao.updateAddress(address);
		if(flag!=false){
			request.setAttribute("update", 1);
			request.getSession().setAttribute("editAddress", address);
		}else{
			request.setAttribute("update", 0);
		}
		return mapping.getInputForward();
	}
}