/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.action;

import java.sql.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Address;
import po.Credit;

import dao.IUserDao;
import database.form.UpdateCreditForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-03-2013
 * 
 * XDoclet definition:
 * @struts.action path="/updateCredit" name="updateCreditForm" input="/updateCredit.jsp" scope="request" validate="true"
 */
public class UpdateCreditAction extends Action {
	/*
	 * Generated Methods
	 */
    private IUserDao udao;
    
	public IUserDao getUdao() {
		return udao;
	}

	public void setUdao(IUserDao udao) {
		this.udao = udao;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UpdateCreditForm updateCreditForm = (UpdateCreditForm) form;// TODO Auto-generated method stub
        long number=Long.parseLong((String) request.getSession().getAttribute("creditnumber"));
		System.out.println(number);
		
		Date ex=new Date(0);
		String name=updateCreditForm.getNameoncard();
		int cardcvv2=updateCreditForm.getCardcvv2();
		String cardtype=updateCreditForm.getCardtype();
		String date=updateCreditForm.getYear()+"-"+updateCreditForm.getMonth()+"-01";
		ex=Date.valueOf(date);
		System.out.println(ex);
		String firstname=updateCreditForm.getFirstname();
		String lastname=updateCreditForm.getLastname();
		String phonenumber=updateCreditForm.getPhonenumber();
		String state=updateCreditForm.getState();
		String city=updateCreditForm.getCity();
		String company=updateCreditForm.getCompany();
		String addrline1=updateCreditForm.getAddr1();
		String addrline2=updateCreditForm.getAddr1();
		int zipcode=Integer.parseInt(updateCreditForm.getZipcode());
		Credit credit=new Credit(number,name,ex,cardcvv2,cardtype,lastname,firstname,state,city,company,zipcode,phonenumber,addrline1,addrline2);
		boolean flag=udao.updateCredit(credit);
		if(flag!=false){
			request.setAttribute("updateCredit", 1);
			request.getSession().setAttribute("editCredit", credit);
		}else{
			request.setAttribute("updateCredit", 0);
		}
		return mapping.getInputForward();

	}
}