/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-04-2013
 * 
 * XDoclet definition:
 * @struts.form name="checkOutForm"
 */
public class CheckOutForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** cardnumber property */
	private String cardnumber;

	/** cvv2 property */
	private String cvv2;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the cardnumber.
	 * @return String
	 */
	public String getCardnumber() {
		return cardnumber;
	}

	/** 
	 * Set the cardnumber.
	 * @param cardnumber The cardnumber to set
	 */
	public void setCardnumber(String cardnumber) {
		this.cardnumber = cardnumber;
	}

	/** 
	 * Returns the cvv2.
	 * @return String
	 */
	public String getCvv2() {
		return cvv2;
	}

	/** 
	 * Set the cvv2.
	 * @param cvv2 The cvv2 to set
	 */
	public void setCvv2(String cvv2) {
		this.cvv2 = cvv2;
	}
}