/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package database.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-28-2013
 * 
 * XDoclet definition:
 * @struts.form name="userRegisterForm"
 */
public class UserRegisterForm extends ValidatorForm {
	/*
	 * Generated Methods
	 */
	private String addressline2;


	/** phone property */
	private String phone;

	/** username property */
	private String username;

	/** addressline1 property */
	private String addressline1;

	/** email property */
	private String email;

	/** lastname property */
	private String lastname;

	/** firstname property */
	private String firstname;

	/** password property */
	private String password;

	/** passwordsalt property */
	private String passwordsalt;
	
	private String state;
	
	private String city;
	
	private String zipcode;
	
	private String company;
	
	
	public String getAddressline2() {
		return addressline2;
	}


	public void setAddressline2(String addressline2) {
		this.addressline2 = addressline2;
	}


	public String getPhone() {
		return phone;
	}


	public void setPhone(String phone) {
		this.phone = phone;
	}


	public String getUsername() {
		return username;
	}


	public void setUsername(String username) {
		this.username = username;
	}


	public String getAddressline1() {
		return addressline1;
	}


	public void setAddressline1(String addressline1) {
		this.addressline1 = addressline1;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public String getLastname() {
		return lastname;
	}


	public void setLastname(String lastname) {
		this.lastname = lastname;
	}


	public String getFirstname() {
		return firstname;
	}


	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	public String getPasswordsalt() {
		return passwordsalt;
	}


	public void setPasswordsalt(String passwordsalt) {
		this.passwordsalt = passwordsalt;
	}


	public String getState() {
		return state;
	}


	public void setState(String state) {
		this.state = state;
	}


	public String getCity() {
		return city;
	}


	public void setCity(String city) {
		this.city = city;
	}


	public String getZipcode() {
		return zipcode;
	}


	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}


	public String getCompany() {
		return company;
	}


	public void setCompany(String company) {
		this.company = company;
	}


	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	
	
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}